# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678ba86e0f0c9ff813158beff715626c383e68b26fe482c7f0185cc74cea1f8e6bfad7f88be7044dfd3f5ba553867875adad63fef8a7aa5e299830ea03a93ee1

test:
  secret_key_base: 6e44721220db5eb217cf63a19d86a4484133fb0c44462314f3e94cb3c1567fc2e1c7b6384d97f710880dd9a039775de3dd2a59c5b912796c3d96b7408fd0b7eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>